### ISSUE TITLE
로그인 기능 구현(JWT)

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#102]
## 요약
로그인 기능 구현

### 해야할 일
**우선 순위**
- [x] JWT에 대한 이해 및 조사
- [x] 프론트에서 JWT를 구현하기 위한 이해 및 조사
- [x] GET 요청으로 백엔드에서 토큰을 받아오는 로직 구현
- [x] 토큰을 받아온 이후 쿠키에 토큰을 저장
- [x] 토큰을 매 API 요청때마다 헤더에 실어보내는 로직 구현

**후 순위**
- [x] 카카오 로그인과 SNS 로그인(파이어 베이스)를 섞어서 사용할 경우 JWT를 어떻게 이용해야하는지 조사
- [x] 기타 로그인에 대해서 프론트가 처리하는 베스트 프랙티스 조사

**Comment by IGhost-P** [comment]
파이어베이스를 이용해 로그인을 한다면, 사용자의 정보는 파이어베이스 데이터베이스에 등록이 되는데 이것이 woo의 데이터베이스와 연동이 되나요..? 저도 한번 찾아보도록 하겠습니다..

**Comment by mdgarden** [comment]
[조사결과](https://github.com/EasyAndBeauty/DailyReceipt-FE-WEB/discussions/32)를 바탕으로 태스크 수정했습니다.
파이어베이스 구현 여부는 백엔드에서 정해야할 것 같습니다.

**Comment by mdgarden** [comment]
## Todo
### Waiting
- [ ] 백엔드 액세스토큰 재발급 api 연결
- [ ] 액세스 토큰 재발급 후 로컬 스토리티, 스테이트에 재발급 받은 토큰으로 갱신
- [ ] 백엔드 인가코드 전달 후 액세스토큰, 리프레쉬 토큰이 어떻게 돌아오는지 확인 후 연결
    - [ ] 프론트에서 refresh토큰의 남은 만료기간을 확인
    - [ ] 최초 앱 구동시 로그인 여부 확인하는 로직
    - [ ] 만료기간이 지나있을 시 모든 토큰 파기 및 스테이트 갱신
- [ ] #126 useDataFetch 로직 전반적 재점검 및 동작확인

## 메모
### 백엔드 확인 내용
- get `{baseURL}/auth/kakao/callback?code=${code}`의 return 값
- 액세스토큰의 재발급 API의 패스와 return 값
- 토큰이 없을 때 또는 유효하지않을 때 반환되는 오류코드
- 그 외 각 API들이 오류를 반환하는 상황과 코드들

**Comment by mdgarden** [comment]
#139 로 이동
