### ISSUE TITLE
[issue] 전반적 레이아웃 / CSS 버그 수정

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#192]
## Todo

- [x] 전체 body에서 스크롤을 안보이게 하기
- [x] 769px 이하 / 이상일 때 동일하게 레이아웃 유지하기
    - [x] 769px 이하일 때 마이페이지가 중앙에 오게 하기
- [x] 각종 고정값들을 동적으로 변경(마진, 패딩 등등)
- [x] 영수증들이 제각각 높이가 다른 이유 조사하고 수정
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/66259746/202206129-84e66598-8202-4522-9318-67d2c7e61a1c.png">
<img width="384" alt="image" src="https://user-images.githubusercontent.com/66259746/202206621-0eebf072-3ef9-4ac8-83c6-ad1370ffda5f.png">
