### ISSUE TITLE
[issue] 닉네임 수정 기능 연결

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#193]
## 요약
닉네임 수정 기능 구현

## Todo
- [x] 사용자 정보 API 연결
    - [x] GET
    - [x] PUT

### 테스트 케이스
- [ ] 유효성 검사에 부적절한 닉네임 입력 시 닉네임 수정이 불가할 것
    - [x] 공백일 때
    - [x] 7글자가 넘었을 때
- [x] 특수문자, 공백을 넣었을 때 닉네임 수정이 가능할 것 (공백만 안됨) 
- [ ] 닉네임을 수정했을 때 마이페이지의 화면에 표시되는 닉네임도 같이 수정되어있을 것
- [x] 닉네임 수정 후 새 탭을 열어서 마이페이지에 접속 -> 닉네임이 수정되어있는지 확인

**Comment by mdgarden** [comment]
특수문자를 넣었을 때 4글자부터 7글자 제한 표시가 뜸
