### ISSUE TITLE
[issue] 각 영수증을 클릭했을 때 해당 날짜의 영수증 출력 페이지로 이동하기

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#194]
## 요약
마이페이지에서 영수증을 클릭했을 때, 해당 날짜의 영수증 출력 페이지로 이동하는 기능 구현

## Todo
- [x] 마이페이지에서 영수증을 클릭했을 때, 해당 날짜의 영수증 출력 페이지로 이동

## 테스트 케이스
- [x] 마이페이지에서 영수증을 클릭했을 때, 해당 날짜의 영수증 출력 페이지로 이동할 것
- [x] 출력 페이지에서 뒤로 가기를 눌렀을 때, 마이 페이지로 이동할 것
- [x] 마이페이지에서 출력 페이지로 이동한 후, 출력 페이지의 핀 아이콘이 "pinned" 상태일 것

**Comment by gygy7151** [comment]
아아 이 부분 구현해야 되는 거군요!
확인했습니당! @mdgarden

**Comment by mdgarden** [comment]
1. 기존 데이터 구조를 API에 맞춰 변경
2. todos[]안에서 날짜 취득 후 해당 날짜로 이동
3. 해당 날짜로 이동하도록 뒤로가기 버튼 수정
