### ISSUE TITLE
[issue] 영수증 핀 /  핀 해제 기능 연결

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#195]
## 요약
영수증의 핀/ 핀 해제 기능 API 연결 및 UI 연결

## Todo
- [ ] 영수증 API 연결
    - [ ] PUT
    - [ ] GET

## 테스트 케이스
- [x] 투두리스트 화면에서 영수증 출력화면으로 넘어갔을 때, 영수증에 핀표시가 되어있지않을것.
- [ ] 영수증 출력화면에서 핀 지정 후, 마이페이지로 이동했을 때 핀 한 영수증이 보일 것
- [ ] 영수증 출력화면에서 핀 지정 후, 핀을 해제. 핀을 해제한 상태에서 마이페이지로 이동했을 때 해당 영수증이 보이지 않을 것.
- [ ] 핀 된 영수증이 없을 경우, 마이페이지에서 문구가 출력될 것.
- [ ] 핀 된 영수증이 있을 경우, 마이페이지에서 해당 영수증을 클릭하여 출력 화면으로 이동할 것.
    - [ ] 이동한 출력 화면에서 영수증의 내용이 일치하는지 확인할 것.
    - [ ] 이동한 출력 화면에서 영수증의 핀이 지정되어있는 상태인지 확인할 것.
- [ ] 이동한 출력 화면에서 영수증의 핀을 해제 후, 마이페이지로 돌아갔을 때 해당 영수증이 마이페이지에서 보이지 않을 것.
    - [ ] 뒤로가기 버튼을 눌렀을 때
    - [ ] 직접 URL을 입력해서 이동했을 때  
- [ ] 다수의 영수증에 핀을 한 이후, 마이페이지에서 해당 영수증들이 보일 것
- [ ] 마이페이지에서 영수증 위에 출력되는 날짜가 "영수증을 출력을 눌렀던 투두리스트 화면상의 날짜"일 것. (영수증을 핀 지정한 실제 날짜X)
